
  name: pyregius
  version: git # just for humans, typically '1.2+git' or '1.3.2'
  summary: IDE para desarrollo en python
  description: |
    Python Regius quiere ser un IDE para python, hecho en python.
    
  architectures:
  - build-on: [amd64, i386]
    run-on: [amd64, i386]

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  apps:
    regius:
      command: main.py
  parts:
    testapp:
      plugin: python
      python-version: python3
      source: .
      python-packages: [python3-pip python3-gi python3-docutils gir1.2-gtksource-3.0 \
            gir1.2-webkit2-4.0 gir1.2-gtkspell3-3.0]
  
