
  name: pyregius
  version: git # just for humans, typically '1.2+git' or '1.3.2'
  summary: IDE para desarrollo en python
  description: |
    Python Regius quiere ser un IDE para python, hecho en python.
    
  architectures:
  - build-on: [amd64, i386]
    run-on: [amd64, i386]

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  apps:
    pyregius:
      command: src/pyregius.py
  parts:
    pyregius:
      plugin: python
      python-version: python3
      prepare: |
            chmod +x src/pyregius.py
      #source: ../  #http://dmnfarrell.github.io/software/python-snap
      #python-packages: 
      build-packages: [
        python3-gi,
        python3-gi-cairo,
        gir1.2-gtk-3.0,
        tango-icon-theme,
        libgirepository1.0-dev,
        gcc,
        libcairo2-dev,
        pkg-config,
        python3-dev,
        python3-venv,
        python3-wheel,
        libgirepository1.0-dev,
        build-essential,
        libbz2-dev,
        libreadline-dev,
        libssl-dev,
        zlib1g-dev,
        libsqlite3-dev,
        wget,
        curl,
        llvm,
        libncurses5-dev,
        libncursesw5-dev,
        xz-utils,
        tk-dev,
        libcairo2-dev,
        gir1.2-gtk-3.0
      ]
  
